version: '3'

vars:
  PROTO_DIR: ./proto
  PROTO_PATH: ./proto/sso/*.proto
  GEN_PATH: ./gen/go

tasks:
  init:
    cmds:
      - mkdir -p {{.GEN_PATH}}
    silent: true

  tidy:
    cmds:
      - go fmt ./...
      - go mod tidy -v
    silent: true

  proto.gen:
    aliases:
      - gen
    desc: "Generate code from proto files"
    cmds:
      - |
        protoc -I {{.PROTO_DIR}} {{.PROTO_PATH}} \
          --go_out={{.GEN_PATH}} \
          --go_opt=paths=source_relative \
          --go-grpc_out={{.GEN_PATH}} \
          --go-grpc_opt=paths=source_relative
    silent: true

